sudo: required
services:
  - docker

before_install:
  - docker build -t maxvfischer/docker-k8s-course -f Dockerfile.dev .

script:
  - docker run -e CI=true maxvfischer/docker-k8s-course npm run test

deploy:
  edge: true
  provider: elasticbeanstalk
  region: "eu-north-1"
  app: "docker-k8s-course"
  env: "dockerk8scourse-env"
  bucket_name: "elasticbeanstalk-eu-north-1-283799098295"
  bucket_path: "docker-k8s-course"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
